const TEXTURE_SIZE_PX = 1024.0;

const TEXTURE_INNER_PADDING = 0;
const TEXTURE_INNER_PADDING_ADJUSTMENT = 2.0;
const TEXTURE_IMAGE_SIZE_PX = 129;

const TILE_UNIT_PX = TEXTURE_IMAGE_SIZE_PX - (2 * TEXTURE_INNER_PADDING_ADJUSTMENT);
const TIGHTNESS_PX = TEXTURE_INNER_PADDING + TEXTURE_INNER_PADDING_ADJUSTMENT;

const TILE_L_0 = TIGHTNESS_PX / TEXTURE_SIZE_PX;
const TILE_L_1 = ((2 * TIGHTNESS_PX + TILE_UNIT_PX) + TIGHTNESS_PX) / TEXTURE_SIZE_PX;
const TILE_L_2 = (((2 * TIGHTNESS_PX + TILE_UNIT_PX) * 2) + TIGHTNESS_PX) / TEXTURE_SIZE_PX;
const TILE_B_0 = (TEXTURE_SIZE_PX - ((2 * TIGHTNESS_PX + TILE_UNIT_PX) * 1) + TIGHTNESS_PX) / TEXTURE_SIZE_PX;
const TILE_B_1 = (TEXTURE_SIZE_PX - ((2 * TIGHTNESS_PX + TILE_UNIT_PX) * 2) + TIGHTNESS_PX) / TEXTURE_SIZE_PX;
const TILE_B_2 = (TEXTURE_SIZE_PX - ((2 * TIGHTNESS_PX + TILE_UNIT_PX) * 3) + TIGHTNESS_PX) / TEXTURE_SIZE_PX;

const TILE_MAIN = {l:TILE_L_1,b:TILE_B_0,name:'TILE_MAIN'};
const TILE_ENTRANCE = {l:TILE_L_0,b:TILE_B_0,name:'TILE_ENTRANCE'};
const TILE_DESERT_BOTTOM_LEFT = {l:TILE_L_0,b:TILE_B_1,name:'TILE_DESERT_BOTTOM_LEFT'};
const TILE_DESERT_BOTTOM_RIGHT = {l:TILE_L_1,b:TILE_B_1,name:'TILE_DESERT_BOTTOM_RIGHT'};
const TILE_DESERT_TOP_LEFT = {l:TILE_L_1,b:TILE_B_2,name:'TILE_DESERT_TOP_LEFT'};
const TILE_DESERT_TOP_RIGHT = {l:TILE_L_2,b:TILE_B_0,name:'TILE_DESERT_TOP_RIGHT'};
const TILE_DESERT_TOP = {l:TILE_L_0,b:TILE_B_2,name:'TILE_DESERT_TOP'};
const TILE_DESERT_ROCK_MAIN = {l:TILE_L_1,b:TILE_B_0,name:'TILE_DESERT_ROCK_MAIN'};
const TILE_TREE = {l:TILE_L_2,b:TILE_B_1,name:'TILE_TREE'};

const TILE_ST_UNIT = TILE_UNIT_PX / TEXTURE_SIZE_PX;
